version: '3'

volumes:
  pg_data:
  STATIC:
  MEDIA:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pa2ha/kittigram_backend
    env_file: .env
    volumes:
      - STATIC:/backend_static
      - MEDIA:/media/
  frontend:
    env_file: .env
    image: pa2ha/kittigram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - STATIC:/frontend_static
  gateway:
    image: pa2ha/kittygram_ngnix
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - STATIC:/staticfiles/
      - MEDIA:/media/
    depends_on:
      - backend